### ISSUE TITLE
Double-check if xlink SVG attribute tests are proper

### ISSUE THREAD

**Issue by queengooborg** [openwebdocs/mdn-bcd-collector#1031]
In https://github.com/openwebdocs/mdn-bcd-collector/pull/990, an update to the `xlink:*` SVG attribute tests was made.  However, I noticed that for Firefox, these tests seem to be passing even when the SVG element itself isn't supported (for example, the `<cursor>` element).  We need to double-check to make sure these tests are working as expected.

**Comment by Elchi3** [comment]
I guess the problem is the usage of `Document.createElementNS()`. It seems to allow creating nonexistent SVG elements. There is no validation going on. Maybe we need to also run `testObjectName(instance, 'SVGCursorElement')` in this test and in other xlink tests.
