### ISSUE TITLE
Update test api.Document.hasPrivateTokens to api.Document.hasPrivateToken, reflect the recent spec change

### ISSUE THREAD

**Issue by skyclouds2001** [openwebdocs/mdn-bcd-collector#1062]
the `Document.hasPrivateTokens()` has renamed to `Document.hasPrivateToken()` according to the spec https://wicg.github.io/trust-token-api/

spec change issue https://github.com/WICG/trust-token-api/issues/282, spec change pull request https://github.com/WICG/trust-token-api/pull/283

also reference to the browser bug report https://bugs.chromium.org/p/chromium/issues/detail?id=1516070

**Comment by queengooborg** [comment]
We use Webref to determine standard track features to add, so this will be resolved automatically when Webref updates.

**Comment by skyclouds2001** [comment]
Got it!
