### ISSUE TITLE
Overhaul update-bcd.ts

### ISSUE THREAD

**Issue by queengooborg** [openwebdocs/mdn-bcd-collector#257]
The `update-bcd` script is in dire need of an overhaul.  It has become too complicated and not easy to maintain, so bugs are challenging to squash.  The script should be rewritten from the ground up in a multi-stage process.

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/19971 moved this script into BCD and some enhancements are planned. Would it make sense to remove the script from this repo instead after confirming the changes made are exactly the same?

**Comment by Elchi3** [comment]
I opened https://github.com/openwebdocs/mdn-bcd-collector/pull/740
