### ISSUE TITLE
Auto Generate PRs for BCD

### ISSUE THREAD

**Issue by lolaodelola** [openwebdocs/mdn-bcd-collector#726]
We want to be able to generate PRs based on what the update script has done. How should we do this? For example, how should we auto generate a PR for new FireFox releases/changes between major Firefox versions?

Opening this issue here to allow folks especially @Elchi3 @queengooborg  @foolip to begin thinking about this ahead of next Tuesday’s (03/10/2023) meeting.

cc @jugglinmike @mariestaver @mzgoddard

**Comment by queengooborg** [comment]
This project is already being tracked as an Open Web Docs project -- see https://github.com/openwebdocs/project/issues/168.
