### ISSUE TITLE
Run collector for all browsers in the definition of Baseline

### ISSUE THREAD

**Issue by ddbeck** [openwebdocs/mdn-bcd-collector#908]
It'd be nice to run the collector on all browsers in the Baseline core browser set (currently: desktop Chrome, Edge, Firefox, and Safari; Android Chrome and Firefox; iOS Safari), so that discrepancies between closely-related browsers are sure to be real.

There's a clear consumer story for doing this: over on https://github.com/web-platform-dx/web-features/pull/434#pullrequestreview-1755069490, we found a likely error in data not mirrored between between Firefox and Firefox for Android (fixed in https://github.com/mdn/browser-compat-data/pull/21388). web-features is already consuming (and aggregating) data across desktop and mobile browsers, satisfying a need for high-quality data.

This could have a few other benefits:

- Better data quality for MDN, Caniuse
- Mirroring would be safer (knowing that discrepancies would be automatically detected)
- Mirroring could be potentially be enforced in the future, when it applies

**Comment by queengooborg** [comment]
I have now started running the collector again on Safari iOS and Chrome, Firefox, Samsung Internet and WebView on Android!
